"""empty message

Revision ID: eb4529604cdf
Revises: 
Create Date: 2018-03-21 22:25:56.102161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4529604cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('user_profile')
    # ### end Alembic commands ###


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user_profile',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    # sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    # sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    # sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'user_profile_pkey'),
    # sa.UniqueConstraint('username', name=u'user_profile_username_key')
    # )
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
